apply from: gradle.ext.sharedModulesConstants

buildscript {
    apply from: gradle.ext.sharedModulesConstants
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.48'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    configurations.all {
        resolutionStrategy.force "com.squareup.okhttp3:okhttp:$okhttpVersion"
        resolutionStrategy.force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"
        resolutionStrategy.force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"
        resolutionStrategy.force "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
        resolutionStrategy.force "org.jetbrains.kotlinx:kotlinx-coroutines-android:$kotlinxVersion"
        resolutionStrategy.force "org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinxVersion"
        resolutionStrategy.force "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:$kotlinxVersion"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
