rootProject.name = 'phone-tube'

def projectRoot = settingsDir

gradle.ext.sharedModulesRoot = new File(projectRoot, 'SharedModules')
gradle.ext.sharedModulesConstants = new File(gradle.ext.sharedModulesRoot, 'constants.gradle')
apply from: new File(gradle.ext.sharedModulesRoot, 'core_settings.gradle')

gradle.ext.mediaServiceCoreRoot = new File(projectRoot, 'MediaServiceCore')
apply from: new File(gradle.ext.mediaServiceCoreRoot, 'core_settings.gradle')

gradle.ext.exoplayerRoot = new File(projectRoot, 'exoplayer-amzn-2.10.6')
gradle.ext.exoplayerModulePrefix = 'exoplayer-'
apply from: 'exoplayer-settings.gradle'

include ':app', ':core-media', ':core-playback'
